// angular-app/src/app/components/header/header.ts
import { Component, ElementRef, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ServiceContext } from '../../services/service-context';
import { BackendType } from '../../services/backend-types';
import { environment } from '../../../environments/environment';
import { AuthState } from '../../utils/auth-state';
import { broadcastAuthStateChangeEvent } from '../../utils/auth-events';

@Component({
  selector: 'header-component',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.html',
  styleUrl: './header.css',
})
export class HeaderComponent implements OnInit, OnDestroy {
  credits: number | null = null;
  showProfileMenu = false;

  backendType: BackendType;
  backendTypeLabel: string;

  authService;
  profileService;

  constructor(private elementRef: ElementRef, serviceContext: ServiceContext, private authState: AuthState, private cd: ChangeDetectorRef) {
    const backendTypeEnv = Number(
      environment.BACKEND_TYPE ?? 0
    );
    this.backendType = backendTypeEnv as BackendType;
    this.backendTypeLabel = BackendType[this.backendType];

    this.authService = serviceContext.value.authService;
    this.profileService = serviceContext.value.profileService;
  }

  ngOnInit(): void {
    this.fetchCredits();
    document.addEventListener('mousedown', this.handleClickOutside);
  }

  ngOnDestroy(): void {
    document.removeEventListener('mousedown', this.handleClickOutside);
  }

  async fetchCredits() {
    const user = this.authState.user;
    if (!user) return;

    try {
      const profile = await this.profileService.getUserProfile(user.id);
      this.credits = profile?.credits ?? 0;
    } catch (err) {
      console.error('Error fetching credits:', err);
      this.credits = 0;
    } finally {
      this.cd.detectChanges();
    }
  }

  toggleProfileMenu() {
    this.showProfileMenu = !this.showProfileMenu;
  }

  async handleLogout() {
    await this.authService.signOut();
    broadcastAuthStateChangeEvent();
    window.location.href = '/';
  }

  handleClickOutside = (event: MouseEvent) => {
    if (!this.elementRef.nativeElement.contains(event.target)) {
      this.showProfileMenu = false;
    }
  };
}

// next-app/components/Header.tsx
"use client";

import { useEffect, useState, useRef } from "react";
import { useServices } from "../contexts/ServiceContext";
import { broadcastAuthStateChangeEvent } from "../utils/authEvents";
import { BackendType } from "../contexts/backendTypes";

export default function Header() {
  const { authService, profileService } = useServices();

  const [credits, setCredits] = useState<number | null>(null);
  const [showProfileMenu, setShowProfileMenu] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const fetchCredits = async () => {
    const user = await authService.getUser();
    if (!user) return;

    try {
      const profile = await profileService.getUserProfile(user.id);
      setCredits(profile?.credits ?? 0);
    } catch (err) {
      console.error("Error fetching credits:", err);
      setCredits(0);
    }
  };

  // Fetch credits
  useEffect(() => {
    fetchCredits();
  }, []);

  const handleLogout = async () => {
    await authService.signOut();
    broadcastAuthStateChangeEvent();
    window.location.href = "/";
  };

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setShowProfileMenu(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);


  const backendTypeEnv = Number(process.env.NEXT_PUBLIC_BACKEND_TYPE);
  const backendType = backendTypeEnv as BackendType;

  return (
    <header className="flex justify-between items-center p-4 bg-white shadow-md sticky top-0 left-0 w-full z-10">
      <h1 className="text-xl font-bold">Quick Choice (via {BackendType[backendType]})</h1>

      <div className="relative flex items-center space-x-4" ref={containerRef}>
        <span className="font-semibold">{credits ?? 0} 💎</span>

        <div className="relative">
          <button
            onClick={() => setShowProfileMenu((prev) => !prev)}
            className="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center hover:bg-gray-300"
          >
            <span className="text-gray-700 font-bold">👤</span>
          </button>

          {showProfileMenu && (
            <div className="absolute right-0 top-full mt-2 w-32 bg-white border shadow-md rounded z-20">
              <button
                onClick={handleLogout}
                className="w-full text-left p-2 hover:bg-gray-100 rounded"
              >
                Logout
              </button>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
