// next-app/contexts/ServiceContext.tsx
"use client";

import { createContext, useContext } from "react";
import { IAuthService } from "../shared-backend";
import { IPollService } from "../shared-backend";
import { IProfileService } from "../shared-backend";
import { IVoteService } from "../shared-backend";

export interface ServiceContextValue {
  authService: IAuthService;
  pollService: IPollService;
  profileService: IProfileService;
  voteService: IVoteService;
}

export const ServiceContext = createContext<ServiceContextValue | null>(null);

export function useServices(): ServiceContextValue {
  const context = useContext(ServiceContext);
  if (!context) {
    throw new Error("useServices must be used within a ServiceContext.Provider");
  }
  return context;
}

// angular-app/src/app/services/service-context.ts
import { Injectable } from '@angular/core';
import { IAuthService, IPollService, IProfileService, IVoteService } from '../../../shared-backend';
import { createServicesByType } from './service-factory';
import { BackendType } from './backend-types';

export interface ServiceContextValue {
  authService: IAuthService;
  pollService: IPollService;
  profileService: IProfileService;
  voteService: IVoteService;
}

@Injectable({
  providedIn: 'root'
})
export class ServiceContext {
  private readonly services: ServiceContextValue;

  constructor() {
    this.services = createServicesByType(BackendType.Supabase);
  }

  get value(): ServiceContextValue {
    return this.services;
  }
}
