// angular-app/src/app/auth-callback/callback.ts
// src/app/auth/callback/callback.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ServiceContext } from '../services/service-context';
import { broadcastAuthStateChangeEvent } from '../utils/auth-events';

@Component({
  selector: 'app-callback',
  standalone: true,
  template: `<div>Signing you in…</div>`,
  imports: [], // add CommonModule if you use *ngIf or *ngFor
})
export class Callback implements OnInit {
  authService;

  constructor(private router: Router, serviceContext: ServiceContext) {
    this.authService = serviceContext.value.authService;
  }

  ngOnInit(): void {
    (async () => {
      try {
        await this.authService.restoreFromUrlTokens(window.location.hash);
        const user = await this.authService.getUser();
        if (user) broadcastAuthStateChangeEvent();
        this.router.navigate(['/']);
      } catch (err) {
        console.error(err);
        this.router.navigate(['/']);
      }
    })();
  }
}

// next-app/app/auth/callback/page.tsx
"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useServices } from "../../../contexts/ServiceContext";
import { broadcastAuthStateChangeEvent } from "../../../utils/authEvents";

export default function CallbackPage() {
  const router = useRouter();
  const { authService } = useServices();

  useEffect(() => {
    async function run() {
      try {
        await authService.restoreFromUrlTokens(window.location.hash);

        const user = await authService.getUser();
        if (user) broadcastAuthStateChangeEvent();

        router.replace("/");
      } catch (err) {
        console.error(err);
        router.replace("/");
      }
    }
    run();
  }, [router, authService]);


  return <div>Signing you in…</div>;
}
